In [1]:
# import libraries
import pandas as pd
from glob import glob

In [2]:
# creating a list of separate csv files in a diretory
# all data files are now into list store_csv
store_csv = sorted(glob("data1/median_listingprice_*.csv"))
store_csv

['data1\\median_listingprice_1br.csv',
 'data1\\median_listingprice_2br.csv',
 'data1\\median_listingprice_3br.csv',
 'data1\\median_listingprice_4br.csv',
 'data1\\median_listingprice_5br_more.csv',
 'data1\\median_listingprice_condo.csv',
 'data1\\median_listingprice_sfr.csv']

In [3]:
# concatinate all separate CSV files into one dataframe
combined_data = pd.concat((pd.read_csv(file).assign(filename = file)
           for file in store_csv), ignore_index = True)
combined_data

,regionname,city,state,metro,countyname,sizerank,2010_01,2010_02,2010_03,2010_04,...,2017_01,2017_02,2017_03,2017_04,2017_05,2017_06,2017_07,2017_08,2017_09,filename
0,28202,Charlotte,NC,Charlotte,Mecklenburg,1br,NaN,NaN,NaN,NaN,...,259900.0,252450.0,253700,255000.0,247900.0,239890.0,246250.0,249900.0,239900.0,data1\median_listingprice_1br.csv
1,28203,Charlotte,NC,Charlotte,Mecklenburg,2br,NaN,NaN,NaN,NaN,...,345000.0,350000.0,351100,350000.0,355450.0,355900.0,360000.0,357500.0,325000.0,data1\median_listingprice_2br.csv
2,28202,Charlotte,NC,Charlotte,Mecklenburg,2br,NaN,NaN,NaN,NaN,...,427500.0,402387.0,375000,350000.0,345000.0,345000.0,345000.0,339450.0,375000.0,data1\median_listingprice_2br.csv
3,28269,Charlotte,NC,Charlotte,Mecklenburg,2br,NaN,NaN,NaN,NaN,...,126000.0,122500.0,125000,126000.0,125500.0,130000.0,133900.0,134950.0,130000.0,data1\median_listingprice_2br.csv
4,28205,Charlotte,NC,Charlotte,Mecklenburg,2br,NaN,NaN,NaN,NaN,...,176500.0,181450.0,180000,211000.0,235000.0,225000.0,225000.0,250000.0,246000.0,data1\median_listingprice_2br.csv
5,28277,Charlotte,NC,Charlotte,Mecklenburg,2br,144900.0,145000.0,138450.0,134900.0,...,189900.0,186450.0,169900,169900.0,184900.0,185000.0,183950.0,189000.0,189900.0,data1\median_listingprice_2br.csv
6,28031,Cornelius,NC,Charlotte,Mecklenburg,2br,NaN,NaN,NaN,NaN,...,198950.0,185000.0,185000,189900.0,171750.0,179000.0,175000.0,177450.0,200000.0,data1\median_listingprice_2br.csv
7,28105,Matthews,NC,Charlotte,Mecklenburg,3br,156500.0,157000.0,159900.0,162000.0,...,235000.0,242400.0,250000,267450.0,259000.0,258000.0,249500.0,250000.0,240000.0,data1\median_listingprice_3br.csv
8,28213,Charlotte,NC,Charlotte,Mecklenburg,3br,NaN,NaN,NaN,NaN,...,159700.0,154900.0,142500,149900.0,155900.0,155900.0,162500.0,169900.0,169900.0,data1\median_listingprice_3br.csv
9,28212,Charlotte,NC,Charlotte,Mecklenburg,3br,NaN,NaN,NaN,NaN,...,135000.0,141250.0,144900,145787.0,169950.0,175000.0,175000.0,169945.0,170000.0,data1\median_listingprice_3br.csv
10,28273,Charlotte,NC,Charlotte,Mecklenburg,3br,139900.0,139900.0,139990.0,137000.0,...,179500.0,182795.0,189500,189900.0,192500.0,192500.0,193950.0,193950.0,199900.0,data1\median_listingprice_3br.csv
11,28214,Charlotte,NC,Charlotte,Mecklenburg,3br,NaN,NaN,NaN,NaN,...,128990.0,139900.0,140000,156250.0,157900.0,160000.0,160000.0,159900.0,159900.0,data1\median_listingprice_3br.csv
12,28269,Charlotte,NC,Charlotte,Mecklenburg,3br,NaN,NaN,NaN,NaN,...,162500.0,173785.0,174900,176450.0,180000.0,186000.0,184950.0,184000.0,184900.0,data1\median_listingprice_3br.csv
13,28031,Cornelius,NC,Charlotte,Mecklenburg,3br,229200.0,225000.0,225000.0,225000.0,...,339500.0,339500.0,340000,349450.0,342000.0,329900.0,320000.0,329900.0,330445.0,data1\median_listingprice_3br.csv
14,28211,Charlotte,NC,Charlotte,Mecklenburg,3br,NaN,NaN,NaN,NaN,...,412450.0,370000.0,412450,439000.0,460000.0,489950.0,445000.0,435000.0,427500.0,data1\median_listingprice_3br.csv
15,28270,Charlotte,NC,Charlotte,Mecklenburg,3br,209000.0,209000.0,206000.0,200000.0,...,274900.0,283000.0,274900,289900.0,284000.0,288000.0,278950.0,279900.0,306950.0,data1\median_listingprice_3br.csv
16,28078,Huntersville,NC,Charlotte,Mecklenburg,3br,207000.0,200000.0,205000.0,204999.0,...,254499.0,242900.0,244900,250000.0,265000.0,269000.0,265000.0,271200.0,275000.0,data1\median_listingprice_3br.csv
17,28278,Charlotte,NC,Charlotte,Mecklenburg,3br,173450.0,179900.0,175000.0,174000.0,...,248900.0,229450.0,239450,243175.0,259995.0,257260.0,259857.5,262499.0,275000.0,data1\median_listingprice_3br.csv
18,28203,Charlotte,NC,Charlotte,Mecklenburg,3br,NaN,NaN,NaN,NaN,...,440000.0,450450.0,450900,458450.0,460000.0,475000.0,482450.0,524900.0,484385.0,data1\median_listingprice_3br.csv
19,28210,Charlotte,NC,Charlotte,Mecklenburg,3br,213445.0,219900.0,229900.0,229000.0,...,287450.0,288700.0,309500,317000.0,319000.0,312500.0,310000.0,309250.0,309950.0,data1\median_listingprice_3br.csv
20,28215,Charlotte,NC,Charlotte,Mecklenburg,3br,NaN,NaN,NaN,NaN,...,140900.0,152466.0,159000,159900.0,155000.0,159000.0,164900.0,162500.0,169900.0,data1\median_listingprice_3br.csv
21,28216,Charlotte,NC,Charlotte,Mecklenburg,3br,NaN,NaN,NaN,NaN,...,135000.0,144999.0,152450,149947.5,152250.0,150000.0,150000.0,152450.0,155000.0,data1\median_listingprice_3br.csv
22,28205,Charlotte,NC,Charlotte,Mecklenburg,3br,NaN,NaN,NaN,NaN,...,282500.0,289000.0,289900,289900.0,299000.0,300000.0,299000.0,300000.0,299999.5,data1\median_listingprice_3br.csv
23,28227,Mint Hill,NC,Charlotte,Mecklenburg,3br,NaN,NaN,NaN,NaN,...,208150.0,203499.5,199900,198949.5,207000.0,218949.5,214900.0,207450.0,199900.0,data1\median_listingprice_3br.csv
24,28036,Davidson,NC,Charlotte,Mecklenburg,3br,255000.0,249900.0,249945.0,255000.0,...,317700.0,317500.0,319900,339000.0,336950.0,337000.0,330000.0,314950.0,324950.0,data1\median_listingprice_3br.csv
25,28277,Charlotte,NC,Charlotte,Mecklenburg,3br,209450.0,210000.0,205000.0,208500.0,...,274950.0,274950.0,274850,282450.0,279950.0,285000.0,280000.0,284900.0,299900.0,data1\median_listingprice_3br.csv
26,28262,Charlotte,NC,Charlotte,Mecklenburg,3br,133450.0,129900.0,129000.0,127900.0,...,147000.0,159000.0,165000,167450.0,169900.0,169900.0,169900.0,172500.0,174900.0,data1\median_listingprice_3br.csv
27,28226,Charlotte,NC,Charlotte,Mecklenburg,3br,NaN,NaN,NaN,NaN,...,339000.0,299900.0,289900,336950.0,312950.0,315000.0,319000.0,323450.0,329900.0,data1\median_listingprice_3br.csv
28,28214,Charlotte,NC,Charlotte,Mecklenburg,4br,135000.0,139900.0,146400.0,149900.0,...,199450.0,199000.0,199450,226470.0,229500.0,231240.0,234900.0,249490.0,235000.0,data1\median_listingprice_4br.csv
29,28031,Cornelius,NC,Charlotte,Mecklenburg,4br,NaN,NaN,NaN,NaN,...,582250.0,595000.0,612500,672000.0,649000.0,609348.5,580000.0,575000.0,554500.0,data1\median_listingprice_4br.csv
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45,28031,Cornelius,NC,Charlotte,Mecklenburg,5br+,NaN,NaN,NaN,NaN,...,1180000.0,1279000.0,1177500,1249999.0,1387500.0,1300000.0,1499500.0,1499999.0,1649000.0,data1\median_listingprice_5br_more.csv
46,28211,Charlotte,NC,Charlotte,Mecklenburg,5br+,NaN,NaN,NaN,NaN,...,1250000.0,1398000.0,1398000,1398500.0,1325000.0,1292000.0,1299000.0,1100000.0,1125000.0,data1\median_listingprice_5br_more.csv
47,28270,Charlotte,NC,Charlotte,Mecklenburg,5br+,517950.0,525000.0,537000.0,525000.0,...,620249.5,599000.0,625000,635499.0,630000.0,656499.0,659900.0,675249.5,689000.0,data1\median_listingprice_5br_more.csv
48,28278,Charlotte,NC,Charlotte,Mecklenburg,5br+,NaN,NaN,NaN,NaN,...,383445.0,365060.0,403990,411945.0,399932.0,401744.5,407999.0,410244.5,429999.0,data1\median_listingprice_5br_more.csv
49,28078,Huntersville,NC,Charlotte,Mecklenburg,5br+,349900.0,347437.5,357289.0,365289.0,...,512499.5,494499.5,535000,509000.0,494950.0,492728.0,493614.0,486200.0,479900.0,data1\median_listingprice_5br_more.csv
50,28277,Charlotte,NC,Charlotte,Mecklenburg,condo,NaN,NaN,NaN,NaN,...,204900.0,200000.0,202450,200000.0,204000.0,223000.0,205500.0,209950.0,199995.0,data1\median_listingprice_condo.csv
51,28203,Charlotte,NC,Charlotte,Mecklenburg,condo,NaN,NaN,NaN,NaN,...,355900.0,355900.0,355900,337250.0,345000.0,352450.0,313950.0,310000.0,299500.0,data1\median_listingprice_condo.csv
52,28202,Charlotte,NC,Charlotte,Mecklenburg,condo,281950.0,278900.0,274950.0,272000.0,...,335000.0,317000.0,315000,325000.0,300000.0,312325.0,309900.0,289900.0,299999.5,data1\median_listingprice_condo.csv
53,28262,Charlotte,NC,Charlotte,Mecklenburg,sfr,144900.0,146000.0,144900.0,143900.0,...,190000.0,190000.0,199900,199949.5,199900.0,194500.0,184900.0,195000.0,198862.0,data1\median_listingprice_sfr.csv
54,28226,Charlotte,NC,Charlotte,Mecklenburg,sfr,NaN,NaN,NaN,NaN,...,467945.0,461200.0,471445,525000.0,499950.0,499000.0,475000.0,469900.0,484688.5,data1\median_listingprice_sfr.csv
55,28105,Matthews,NC,Charlotte,Mecklenburg,sfr,219000.0,209950.0,206700.0,214750.0,...,294750.0,297000.0,299999,309500.0,304700.0,312450.0,299950.0,300000.0,295000.0,data1\median_listingprice_sfr.csv
56,28213,Charlotte,NC,Charlotte,Mecklenburg,sfr,NaN,NaN,NaN,NaN,...,157650.0,155000.0,142500,149900.0,155900.0,156500.0,166075.0,170000.0,170000.0,data1\median_listingprice_sfr.csv
57,28212,Charlotte,NC,Charlotte,Mecklenburg,sfr,NaN,NaN,NaN,NaN,...,135000.0,141250.0,142500,157500.0,167449.5,175000.0,177350.0,175450.0,179900.0,data1\median_listingprice_sfr.csv
58,28269,Charlotte,NC,Charlotte,Mecklenburg,sfr,145600.0,143900.0,144900.0,147450.0,...,180000.0,187500.0,192000,210000.0,213000.0,225000.0,220000.0,214900.0,209900.0,data1\median_listingprice_sfr.csv
59,28273,Charlotte,NC,Charlotte,Mecklenburg,sfr,142900.0,142500.0,144000.0,139900.0,...,190950.0,195000.0,199250,199900.0,209995.0,210000.0,200000.0,199999.0,218500.0,data1\median_listingprice_sfr.csv
60,28214,Charlotte,NC,Charlotte,Mecklenburg,sfr,NaN,NaN,NaN,NaN,...,144950.0,151990.0,155000,176500.0,179900.0,179995.0,180000.0,179900.0,178950.0,data1\median_listingprice_sfr.csv
61,28031,Cornelius,NC,Charlotte,Mecklenburg,sfr,NaN,NaN,NaN,NaN,...,398900.0,399999.0,419700,449060.0,442000.0,425000.0,418250.0,410909.5,420322.0,data1\median_listingprice_sfr.csv
62,28211,Charlotte,NC,Charlotte,Mecklenburg,sfr,NaN,NaN,NaN,NaN,...,559000.0,575000.0,595000,659000.0,670000.0,649950.0,599000.0,556445.0,555672.5,data1\median_listingprice_sfr.csv
63,28270,Charlotte,NC,Charlotte,Mecklenburg,sfr,297000.0,298000.0,290000.0,289950.0,...,479450.0,489000.0,496990,496990.0,479000.0,469900.0,450000.0,439949.5,449000.0,data1\median_listingprice_sfr.csv
64,28078,Huntersville,NC,Charlotte,Mecklenburg,sfr,250000.0,249900.0,248700.0,245450.0,...,329000.0,324900.0,334945,339900.0,340000.0,340990.0,339250.0,344990.0,344990.0,data1\median_listingprice_sfr.csv
65,28209,Charlotte,NC,Charlotte,Mecklenburg,sfr,NaN,NaN,NaN,NaN,...,462000.0,462000.0,455000,467500.0,474950.0,474950.0,449000.0,419900.0,425000.0,data1\median_listingprice_sfr.csv
66,28210,Charlotte,NC,Charlotte,Mecklenburg,sfr,256250.0,250000.0,259000.0,264500.0,...,339888.0,345000.0,358500,389000.0,389900.0,379450.0,364900.0,364900.0,377487.5,data1\median_listingprice_sfr.csv
67,28278,Charlotte,NC,Charlotte,Mecklenburg,sfr,219000.0,219000.0,209950.0,209000.0,...,326945.0,314942.5,312995,305195.0,313217.0,314058.5,315000.0,325000.0,331370.0,data1\median_listingprice_sfr.csv
68,28215,Charlotte,NC,Charlotte,Mecklenburg,sfr,NaN,NaN,NaN,NaN,...,149000.0,159000.0,165000,169000.0,165000.0,165000.0,169999.0,175000.0,179000.0,data1\median_listingprice_sfr.csv
69,28216,Charlotte,NC,Charlotte,Mecklenburg,sfr,NaN,NaN,NaN,NaN,...,152093.0,150000.0,157000,154900.0,153000.0,155000.0,160747.5,159900.0,161500.0,data1\median_listingprice_sfr.csv
70,28205,Charlotte,NC,Charlotte,Mecklenburg,sfr,NaN,NaN,NaN,NaN,...,290750.0,293747.5,299900,317950.0,329500.0,334450.0,329000.0,334900.0,325000.0,data1\median_listingprice_sfr.csv
71,28203,Charlotte,NC,Charlotte,Mecklenburg,sfr,NaN,NaN,NaN,NaN,...,460000.0,460000.0,460000,461950.0,460000.0,499500.0,539500.0,570000.0,489500.0,data1\median_listingprice_sfr.csv
72,28227,Mint Hill,NC,Charlotte,Mecklenburg,sfr,NaN,NaN,NaN,NaN,...,268909.0,262950.0,256030,246200.0,251612.0,259900.0,251900.0,253900.0,252400.0,data1\median_listingprice_sfr.csv
73,28277,Charlotte,NC,Charlotte,Mecklenburg,sfr,285000.0,280950.0,275567.0,278449.5,...,384500.0,379950.0,387000,399000.0,392500.0,391000.0,389900.0,389900.0,399000.0,data1\median_listingprice_sfr.csv
74,28036,Davidson,NC,Charlotte,Mecklenburg,sfr,375000.0,375000.0,385150.0,371776.0,...,465000.0,484900.0,490000,497450.0,520000.0,509900.0,489000.0,469450.0,447000.0,data1\median_listingprice_sfr.csv

In [4]:
# only taking the columns that we needed
final_df = combined_data[["regionname", "countyname", "sizerank", "2017_01",  "2017_02", "2017_03", "2017_04", "2017_05", "2017_06", "2017_07", "2017_08", "2017_09"]]
final_df

,regionname,countyname,sizerank,2017_01,2017_02,2017_03,2017_04,2017_05,2017_06,2017_07,2017_08,2017_09
0,28202,Mecklenburg,1br,259900.0,252450.0,253700,255000.0,247900.0,239890.0,246250.0,249900.0,239900.0
1,28203,Mecklenburg,2br,345000.0,350000.0,351100,350000.0,355450.0,355900.0,360000.0,357500.0,325000.0
2,28202,Mecklenburg,2br,427500.0,402387.0,375000,350000.0,345000.0,345000.0,345000.0,339450.0,375000.0
3,28269,Mecklenburg,2br,126000.0,122500.0,125000,126000.0,125500.0,130000.0,133900.0,134950.0,130000.0
4,28205,Mecklenburg,2br,176500.0,181450.0,180000,211000.0,235000.0,225000.0,225000.0,250000.0,246000.0
5,28277,Mecklenburg,2br,189900.0,186450.0,169900,169900.0,184900.0,185000.0,183950.0,189000.0,189900.0
6,28031,Mecklenburg,2br,198950.0,185000.0,185000,189900.0,171750.0,179000.0,175000.0,177450.0,200000.0
7,28105,Mecklenburg,3br,235000.0,242400.0,250000,267450.0,259000.0,258000.0,249500.0,250000.0,240000.0
8,28213,Mecklenburg,3br,159700.0,154900.0,142500,149900.0,155900.0,155900.0,162500.0,169900.0,169900.0
9,28212,Mecklenburg,3br,135000.0,141250.0,144900,145787.0,169950.0,175000.0,175000.0,169945.0,170000.0
10,28273,Mecklenburg,3br,179500.0,182795.0,189500,189900.0,192500.0,192500.0,193950.0,193950.0,199900.0
11,28214,Mecklenburg,3br,128990.0,139900.0,140000,156250.0,157900.0,160000.0,160000.0,159900.0,159900.0
12,28269,Mecklenburg,3br,162500.0,173785.0,174900,176450.0,180000.0,186000.0,184950.0,184000.0,184900.0
13,28031,Mecklenburg,3br,339500.0,339500.0,340000,349450.0,342000.0,329900.0,320000.0,329900.0,330445.0
14,28211,Mecklenburg,3br,412450.0,370000.0,412450,439000.0,460000.0,489950.0,445000.0,435000.0,427500.0
15,28270,Mecklenburg,3br,274900.0,283000.0,274900,289900.0,284000.0,288000.0,278950.0,279900.0,306950.0
16,28078,Mecklenburg,3br,254499.0,242900.0,244900,250000.0,265000.0,269000.0,265000.0,271200.0,275000.0
17,28278,Mecklenburg,3br,248900.0,229450.0,239450,243175.0,259995.0,257260.0,259857.5,262499.0,275000.0
18,28203,Mecklenburg,3br,440000.0,450450.0,450900,458450.0,460000.0,475000.0,482450.0,524900.0,484385.0
19,28210,Mecklenburg,3br,287450.0,288700.0,309500,317000.0,319000.0,312500.0,310000.0,309250.0,309950.0
20,28215,Mecklenburg,3br,140900.0,152466.0,159000,159900.0,155000.0,159000.0,164900.0,162500.0,169900.0
21,28216,Mecklenburg,3br,135000.0,144999.0,152450,149947.5,152250.0,150000.0,150000.0,152450.0,155000.0
22,28205,Mecklenburg,3br,282500.0,289000.0,289900,289900.0,299000.0,300000.0,299000.0,300000.0,299999.5
23,28227,Mecklenburg,3br,208150.0,203499.5,199900,198949.5,207000.0,218949.5,214900.0,207450.0,199900.0
24,28036,Mecklenburg,3br,317700.0,317500.0,319900,339000.0,336950.0,337000.0,330000.0,314950.0,324950.0
25,28277,Mecklenburg,3br,274950.0,274950.0,274850,282450.0,279950.0,285000.0,280000.0,284900.0,299900.0
26,28262,Mecklenburg,3br,147000.0,159000.0,165000,167450.0,169900.0,169900.0,169900.0,172500.0,174900.0
27,28226,Mecklenburg,3br,339000.0,299900.0,289900,336950.0,312950.0,315000.0,319000.0,323450.0,329900.0
28,28214,Mecklenburg,4br,199450.0,199000.0,199450,226470.0,229500.0,231240.0,234900.0,249490.0,235000.0
29,28031,Mecklenburg,4br,582250.0,595000.0,612500,672000.0,649000.0,609348.5,580000.0,575000.0,554500.0
...,...,...,...,...,...,...,...,...,...,...,...,...
45,28031,Mecklenburg,5br+,1180000.0,1279000.0,1177500,1249999.0,1387500.0,1300000.0,1499500.0,1499999.0,1649000.0
46,28211,Mecklenburg,5br+,1250000.0,1398000.0,1398000,1398500.0,1325000.0,1292000.0,1299000.0,1100000.0,1125000.0
47,28270,Mecklenburg,5br+,620249.5,599000.0,625000,635499.0,630000.0,656499.0,659900.0,675249.5,689000.0
48,28278,Mecklenburg,5br+,383445.0,365060.0,403990,411945.0,399932.0,401744.5,407999.0,410244.5,429999.0
49,28078,Mecklenburg,5br+,512499.5,494499.5,535000,509000.0,494950.0,492728.0,493614.0,486200.0,479900.0
50,28277,Mecklenburg,condo,204900.0,200000.0,202450,200000.0,204000.0,223000.0,205500.0,209950.0,199995.0
51,28203,Mecklenburg,condo,355900.0,355900.0,355900,337250.0,345000.0,352450.0,313950.0,310000.0,299500.0
52,28202,Mecklenburg,condo,335000.0,317000.0,315000,325000.0,300000.0,312325.0,309900.0,289900.0,299999.5
53,28262,Mecklenburg,sfr,190000.0,190000.0,199900,199949.5,199900.0,194500.0,184900.0,195000.0,198862.0
54,28226,Mecklenburg,sfr,467945.0,461200.0,471445,525000.0,499950.0,499000.0,475000.0,469900.0,484688.5
55,28105,Mecklenburg,sfr,294750.0,297000.0,299999,309500.0,304700.0,312450.0,299950.0,300000.0,295000.0
56,28213,Mecklenburg,sfr,157650.0,155000.0,142500,149900.0,155900.0,156500.0,166075.0,170000.0,170000.0
57,28212,Mecklenburg,sfr,135000.0,141250.0,142500,157500.0,167449.5,175000.0,177350.0,175450.0,179900.0
58,28269,Mecklenburg,sfr,180000.0,187500.0,192000,210000.0,213000.0,225000.0,220000.0,214900.0,209900.0
59,28273,Mecklenburg,sfr,190950.0,195000.0,199250,199900.0,209995.0,210000.0,200000.0,199999.0,218500.0
60,28214,Mecklenburg,sfr,144950.0,151990.0,155000,176500.0,179900.0,179995.0,180000.0,179900.0,178950.0
61,28031,Mecklenburg,sfr,398900.0,399999.0,419700,449060.0,442000.0,425000.0,418250.0,410909.5,420322.0
62,28211,Mecklenburg,sfr,559000.0,575000.0,595000,659000.0,670000.0,649950.0,599000.0,556445.0,555672.5
63,28270,Mecklenburg,sfr,479450.0,489000.0,496990,496990.0,479000.0,469900.0,450000.0,439949.5,449000.0
64,28078,Mecklenburg,sfr,329000.0,324900.0,334945,339900.0,340000.0,340990.0,339250.0,344990.0,344990.0
65,28209,Mecklenburg,sfr,462000.0,462000.0,455000,467500.0,474950.0,474950.0,449000.0,419900.0,425000.0
66,28210,Mecklenburg,sfr,339888.0,345000.0,358500,389000.0,389900.0,379450.0,364900.0,364900.0,377487.5
67,28278,Mecklenburg,sfr,326945.0,314942.5,312995,305195.0,313217.0,314058.5,315000.0,325000.0,331370.0
68,28215,Mecklenburg,sfr,149000.0,159000.0,165000,169000.0,165000.0,165000.0,169999.0,175000.0,179000.0
69,28216,Mecklenburg,sfr,152093.0,150000.0,157000,154900.0,153000.0,155000.0,160747.5,159900.0,161500.0
70,28205,Mecklenburg,sfr,290750.0,293747.5,299900,317950.0,329500.0,334450.0,329000.0,334900.0,325000.0
71,28203,Mecklenburg,sfr,460000.0,460000.0,460000,461950.0,460000.0,499500.0,539500.0,570000.0,489500.0
72,28227,Mecklenburg,sfr,268909.0,262950.0,256030,246200.0,251612.0,259900.0,251900.0,253900.0,252400.0
73,28277,Mecklenburg,sfr,384500.0,379950.0,387000,399000.0,392500.0,391000.0,389900.0,389900.0,399000.0
74,28036,Mecklenburg,sfr,465000.0,484900.0,490000,497450.0,520000.0,509900.0,489000.0,469450.0,447000.0

In [5]:
# calculating median for the individual month
median_2017 = final_df[["2017_01", "2017_02", "2017_03", "2017_04", "2017_05", "2017_06", "2017_07", "2017_08", "2017_09"]].median(axis=1)
median_2017

0      249900.0
1      351100.0
2      350000.0
3      126000.0
4      225000.0
5      185000.0
6      185000.0
7      250000.0
8      155900.0
9      169945.0
10     192500.0
11     157900.0
12     180000.0
13     339500.0
14     435000.0
15     283000.0
16     265000.0
17     257260.0
18     460000.0
19     309950.0
20     159000.0
21     150000.0
22     299000.0
23     207000.0
24     324950.0
25     280000.0
26     169900.0
27     319000.0
28     229500.0
29     595000.0
        ...
45    1300000.0
46    1299000.0
47     635499.0
48     403990.0
49     494499.5
50     204000.0
51     345000.0
52     312325.0
53     195000.0
54     475000.0
55     299999.0
56     156500.0
57     167449.5
58     210000.0
59     199999.0
60     178950.0
61     419700.0
62     595000.0
63     479000.0
64     339900.0
65     462000.0
66     364900.0
67     314942.5
68     165000.0
69     155000.0
70     325000.0
71     461950.0
72     253900.0
73     389900.0
74     489000.0
Length: 75, dtype: float64

In [19]:
# appending the mean column into dataframe
final_df["Median_2017"] = median_2017
final_df

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

,Zipcode,County,sizerank,2017_01,2017_02,2017_03,2017_04,2017_05,2017_06,2017_07,2017_08,2017_09,Median_2017
0,28202,Mecklenburg,1br,259900.0,252450.0,253700,255000.0,247900.0,239890.0,246250.0,249900.0,239900.0,249900.0
1,28203,Mecklenburg,2br,345000.0,350000.0,351100,350000.0,355450.0,355900.0,360000.0,357500.0,325000.0,351100.0
2,28202,Mecklenburg,2br,427500.0,402387.0,375000,350000.0,345000.0,345000.0,345000.0,339450.0,375000.0,350000.0
3,28269,Mecklenburg,2br,126000.0,122500.0,125000,126000.0,125500.0,130000.0,133900.0,134950.0,130000.0,126000.0
4,28205,Mecklenburg,2br,176500.0,181450.0,180000,211000.0,235000.0,225000.0,225000.0,250000.0,246000.0,225000.0
5,28277,Mecklenburg,2br,189900.0,186450.0,169900,169900.0,184900.0,185000.0,183950.0,189000.0,189900.0,185000.0
6,28031,Mecklenburg,2br,198950.0,185000.0,185000,189900.0,171750.0,179000.0,175000.0,177450.0,200000.0,185000.0
7,28105,Mecklenburg,3br,235000.0,242400.0,250000,267450.0,259000.0,258000.0,249500.0,250000.0,240000.0,250000.0
8,28213,Mecklenburg,3br,159700.0,154900.0,142500,149900.0,155900.0,155900.0,162500.0,169900.0,169900.0,155900.0
9,28212,Mecklenburg,3br,135000.0,141250.0,144900,145787.0,169950.0,175000.0,175000.0,169945.0,170000.0,169945.0
10,28273,Mecklenburg,3br,179500.0,182795.0,189500,189900.0,192500.0,192500.0,193950.0,193950.0,199900.0,192500.0
11,28214,Mecklenburg,3br,128990.0,139900.0,140000,156250.0,157900.0,160000.0,160000.0,159900.0,159900.0,157900.0
12,28269,Mecklenburg,3br,162500.0,173785.0,174900,176450.0,180000.0,186000.0,184950.0,184000.0,184900.0,180000.0
13,28031,Mecklenburg,3br,339500.0,339500.0,340000,349450.0,342000.0,329900.0,320000.0,329900.0,330445.0,339500.0
14,28211,Mecklenburg,3br,412450.0,370000.0,412450,439000.0,460000.0,489950.0,445000.0,435000.0,427500.0,435000.0
15,28270,Mecklenburg,3br,274900.0,283000.0,274900,289900.0,284000.0,288000.0,278950.0,279900.0,306950.0,283000.0
16,28078,Mecklenburg,3br,254499.0,242900.0,244900,250000.0,265000.0,269000.0,265000.0,271200.0,275000.0,265000.0
17,28278,Mecklenburg,3br,248900.0,229450.0,239450,243175.0,259995.0,257260.0,259857.5,262499.0,275000.0,257260.0
18,28203,Mecklenburg,3br,440000.0,450450.0,450900,458450.0,460000.0,475000.0,482450.0,524900.0,484385.0,460000.0
19,28210,Mecklenburg,3br,287450.0,288700.0,309500,317000.0,319000.0,312500.0,310000.0,309250.0,309950.0,309950.0
20,28215,Mecklenburg,3br,140900.0,152466.0,159000,159900.0,155000.0,159000.0,164900.0,162500.0,169900.0,159000.0
21,28216,Mecklenburg,3br,135000.0,144999.0,152450,149947.5,152250.0,150000.0,150000.0,152450.0,155000.0,150000.0
22,28205,Mecklenburg,3br,282500.0,289000.0,289900,289900.0,299000.0,300000.0,299000.0,300000.0,299999.5,299000.0
23,28227,Mecklenburg,3br,208150.0,203499.5,199900,198949.5,207000.0,218949.5,214900.0,207450.0,199900.0,207000.0
24,28036,Mecklenburg,3br,317700.0,317500.0,319900,339000.0,336950.0,337000.0,330000.0,314950.0,324950.0,324950.0
25,28277,Mecklenburg,3br,274950.0,274950.0,274850,282450.0,279950.0,285000.0,280000.0,284900.0,299900.0,280000.0
26,28262,Mecklenburg,3br,147000.0,159000.0,165000,167450.0,169900.0,169900.0,169900.0,172500.0,174900.0,169900.0
27,28226,Mecklenburg,3br,339000.0,299900.0,289900,336950.0,312950.0,315000.0,319000.0,323450.0,329900.0,319000.0
28,28214,Mecklenburg,4br,199450.0,199000.0,199450,226470.0,229500.0,231240.0,234900.0,249490.0,235000.0,229500.0
29,28031,Mecklenburg,4br,582250.0,595000.0,612500,672000.0,649000.0,609348.5,580000.0,575000.0,554500.0,595000.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
45,28031,Mecklenburg,5br+,1180000.0,1279000.0,1177500,1249999.0,1387500.0,1300000.0,1499500.0,1499999.0,1649000.0,1300000.0
46,28211,Mecklenburg,5br+,1250000.0,1398000.0,1398000,1398500.0,1325000.0,1292000.0,1299000.0,1100000.0,1125000.0,1299000.0
47,28270,Mecklenburg,5br+,620249.5,599000.0,625000,635499.0,630000.0,656499.0,659900.0,675249.5,689000.0,635499.0
48,28278,Mecklenburg,5br+,383445.0,365060.0,403990,411945.0,399932.0,401744.5,407999.0,410244.5,429999.0,403990.0
49,28078,Mecklenburg,5br+,512499.5,494499.5,535000,509000.0,494950.0,492728.0,493614.0,486200.0,479900.0,494499.5
50,28277,Mecklenburg,condo,204900.0,200000.0,202450,200000.0,204000.0,223000.0,205500.0,209950.0,199995.0,204000.0
51,28203,Mecklenburg,condo,355900.0,355900.0,355900,337250.0,345000.0,352450.0,313950.0,310000.0,299500.0,345000.0
52,28202,Mecklenburg,condo,335000.0,317000.0,315000,325000.0,300000.0,312325.0,309900.0,289900.0,299999.5,312325.0
53,28262,Mecklenburg,sfr,190000.0,190000.0,199900,199949.5,199900.0,194500.0,184900.0,195000.0,198862.0,195000.0
54,28226,Mecklenburg,sfr,467945.0,461200.0,471445,525000.0,499950.0,499000.0,475000.0,469900.0,484688.5,475000.0
55,28105,Mecklenburg,sfr,294750.0,297000.0,299999,309500.0,304700.0,312450.0,299950.0,300000.0,295000.0,299999.0
56,28213,Mecklenburg,sfr,157650.0,155000.0,142500,149900.0,155900.0,156500.0,166075.0,170000.0,170000.0,156500.0
57,28212,Mecklenburg,sfr,135000.0,141250.0,142500,157500.0,167449.5,175000.0,177350.0,175450.0,179900.0,167449.5
58,28269,Mecklenburg,sfr,180000.0,187500.0,192000,210000.0,213000.0,225000.0,220000.0,214900.0,209900.0,210000.0
59,28273,Mecklenburg,sfr,190950.0,195000.0,199250,199900.0,209995.0,210000.0,200000.0,199999.0,218500.0,199999.0
60,28214,Mecklenburg,sfr,144950.0,151990.0,155000,176500.0,179900.0,179995.0,180000.0,179900.0,178950.0,178950.0
61,28031,Mecklenburg,sfr,398900.0,399999.0,419700,449060.0,442000.0,425000.0,418250.0,410909.5,420322.0,419700.0
62,28211,Mecklenburg,sfr,559000.0,575000.0,595000,659000.0,670000.0,649950.0,599000.0,556445.0,555672.5,595000.0
63,28270,Mecklenburg,sfr,479450.0,489000.0,496990,496990.0,479000.0,469900.0,450000.0,439949.5,449000.0,479000.0
64,28078,Mecklenburg,sfr,329000.0,324900.0,334945,339900.0,340000.0,340990.0,339250.0,344990.0,344990.0,339900.0
65,28209,Mecklenburg,sfr,462000.0,462000.0,455000,467500.0,474950.0,474950.0,449000.0,419900.0,425000.0,462000.0
66,28210,Mecklenburg,sfr,339888.0,345000.0,358500,389000.0,389900.0,379450.0,364900.0,364900.0,377487.5,364900.0
67,28278,Mecklenburg,sfr,326945.0,314942.5,312995,305195.0,313217.0,314058.5,315000.0,325000.0,331370.0,314942.5
68,28215,Mecklenburg,sfr,149000.0,159000.0,165000,169000.0,165000.0,165000.0,169999.0,175000.0,179000.0,165000.0
69,28216,Mecklenburg,sfr,152093.0,150000.0,157000,154900.0,153000.0,155000.0,160747.5,159900.0,161500.0,155000.0
70,28205,Mecklenburg,sfr,290750.0,293747.5,299900,317950.0,329500.0,334450.0,329000.0,334900.0,325000.0,325000.0
71,28203,Mecklenburg,sfr,460000.0,460000.0,460000,461950.0,460000.0,499500.0,539500.0,570000.0,489500.0,461950.0
72,28227,Mecklenburg,sfr,268909.0,262950.0,256030,246200.0,251612.0,259900.0,251900.0,253900.0,252400.0,253900.0
73,28277,Mecklenburg,sfr,384500.0,379950.0,387000,399000.0,392500.0,391000.0,389900.0,389900.0,399000.0,389900.0
74,28036,Mecklenburg,sfr,465000.0,484900.0,490000,497450.0,520000.0,509900.0,489000.0,469450.0,447000.0,489000.0

In [20]:
# checking the columns before renaming
print(final_df.columns)

Index(['Zipcode', 'County', 'sizerank', '2017_01', '2017_02', '2017_03',
       '2017_04', '2017_05', '2017_06', '2017_07', '2017_08', '2017_09',
       'Median_2017'],
      dtype='object')

In [23]:
# renaming the columns   
final_df.rename(columns = {"regionname": "Zipcode", "countyname": "County"}) 
print(final_df.columns)

Index(['Zipcode', 'County', 'sizerank', '2017_01', '2017_02', '2017_03',
       '2017_04', '2017_05', '2017_06', '2017_07', '2017_08', '2017_09',
       'Median_2017'],
      dtype='object')

In [24]:
print(final_df)

    Zipcode       County sizerank    2017_01    2017_02  2017_03    2017_04  \
0     28202  Mecklenburg      1br   259900.0   252450.0   253700   255000.0
1     28203  Mecklenburg      2br   345000.0   350000.0   351100   350000.0
2     28202  Mecklenburg      2br   427500.0   402387.0   375000   350000.0
3     28269  Mecklenburg      2br   126000.0   122500.0   125000   126000.0
4     28205  Mecklenburg      2br   176500.0   181450.0   180000   211000.0
5     28277  Mecklenburg      2br   189900.0   186450.0   169900   169900.0
6     28031  Mecklenburg      2br   198950.0   185000.0   185000   189900.0
7     28105  Mecklenburg      3br   235000.0   242400.0   250000   267450.0
8     28213  Mecklenburg      3br   159700.0   154900.0   142500   149900.0
9     28212  Mecklenburg      3br   135000.0   141250.0   144900   145787.0
10    28273  Mecklenburg      3br   179500.0   182795.0   189500   189900.0
11    28214  Mecklenburg      3br   128990.0   139900.0   140000   156250.0
12    28269  Mecklenburg      3br   162500.0   173785.0   174900   176450.0
13    28031  Mecklenburg      3br   339500.0   339500.0   340000   349450.0
14    28211  Mecklenburg      3br   412450.0   370000.0   412450   439000.0
15    28270  Mecklenburg      3br   274900.0   283000.0   274900   289900.0
16    28078  Mecklenburg      3br   254499.0   242900.0   244900   250000.0
17    28278  Mecklenburg      3br   248900.0   229450.0   239450   243175.0
18    28203  Mecklenburg      3br   440000.0   450450.0   450900   458450.0
19    28210  Mecklenburg      3br   287450.0   288700.0   309500   317000.0
20    28215  Mecklenburg      3br   140900.0   152466.0   159000   159900.0
21    28216  Mecklenburg      3br   135000.0   144999.0   152450   149947.5
22    28205  Mecklenburg      3br   282500.0   289000.0   289900   289900.0
23    28227  Mecklenburg      3br   208150.0   203499.5   199900   198949.5
24    28036  Mecklenburg      3br   317700.0   317500.0   319900   339000.0
25    28277  Mecklenburg      3br   274950.0   274950.0   274850   282450.0
26    28262  Mecklenburg      3br   147000.0   159000.0   165000   167450.0
27    28226  Mecklenburg      3br   339000.0   299900.0   289900   336950.0
28    28214  Mecklenburg      4br   199450.0   199000.0   199450   226470.0
29    28031  Mecklenburg      4br   582250.0   595000.0   612500   672000.0
..      ...          ...      ...        ...        ...      ...        ...
45    28031  Mecklenburg     5br+  1180000.0  1279000.0  1177500  1249999.0
46    28211  Mecklenburg     5br+  1250000.0  1398000.0  1398000  1398500.0
47    28270  Mecklenburg     5br+   620249.5   599000.0   625000   635499.0
48    28278  Mecklenburg     5br+   383445.0   365060.0   403990   411945.0
49    28078  Mecklenburg     5br+   512499.5   494499.5   535000   509000.0
50    28277  Mecklenburg    condo   204900.0   200000.0   202450   200000.0
51    28203  Mecklenburg    condo   355900.0   355900.0   355900   337250.0
52    28202  Mecklenburg    condo   335000.0   317000.0   315000   325000.0
53    28262  Mecklenburg      sfr   190000.0   190000.0   199900   199949.5
54    28226  Mecklenburg      sfr   467945.0   461200.0   471445   525000.0
55    28105  Mecklenburg      sfr   294750.0   297000.0   299999   309500.0
56    28213  Mecklenburg      sfr   157650.0   155000.0   142500   149900.0
57    28212  Mecklenburg      sfr   135000.0   141250.0   142500   157500.0
58    28269  Mecklenburg      sfr   180000.0   187500.0   192000   210000.0
59    28273  Mecklenburg      sfr   190950.0   195000.0   199250   199900.0
60    28214  Mecklenburg      sfr   144950.0   151990.0   155000   176500.0
61    28031  Mecklenburg      sfr   398900.0   399999.0   419700   449060.0
62    28211  Mecklenburg      sfr   559000.0   575000.0   595000   659000.0
63    28270  Mecklenburg      sfr   479450.0   489000.0   496990   496990.0
64    28078  Mecklenburg      sfr   329000.0   324900.0   334945   339900.0
65    28209  Mecklenburg      sfr   462000.0   462000.0   455000   467500.0
66    28210  Mecklenburg      sfr   339888.0   345000.0   358500   389000.0
67    28278  Mecklenburg      sfr   326945.0   314942.5   312995   305195.0
68    28215  Mecklenburg      sfr   149000.0   159000.0   165000   169000.0
69    28216  Mecklenburg      sfr   152093.0   150000.0   157000   154900.0
70    28205  Mecklenburg      sfr   290750.0   293747.5   299900   317950.0
71    28203  Mecklenburg      sfr   460000.0   460000.0   460000   461950.0
72    28227  Mecklenburg      sfr   268909.0   262950.0   256030   246200.0
73    28277  Mecklenburg      sfr   384500.0   379950.0   387000   399000.0
74    28036  Mecklenburg      sfr   465000.0   484900.0   490000   497450.0

      2017_05    2017_06    2017_07    2017_08    2017_09  Median_2017
0    247900.0   239890.0   246250.0   249900.0   239900.0     249900.0
1    355450.0   355900.0   360000.0   357500.0   325000.0     351100.0
2    345000.0   345000.0   345000.0   339450.0   375000.0     350000.0
3    125500.0   130000.0   133900.0   134950.0   130000.0     126000.0
4    235000.0   225000.0   225000.0   250000.0   246000.0     225000.0
5    184900.0   185000.0   183950.0   189000.0   189900.0     185000.0
6    171750.0   179000.0   175000.0   177450.0   200000.0     185000.0
7    259000.0   258000.0   249500.0   250000.0   240000.0     250000.0
8    155900.0   155900.0   162500.0   169900.0   169900.0     155900.0
9    169950.0   175000.0   175000.0   169945.0   170000.0     169945.0
10   192500.0   192500.0   193950.0   193950.0   199900.0     192500.0
11   157900.0   160000.0   160000.0   159900.0   159900.0     157900.0
12   180000.0   186000.0   184950.0   184000.0   184900.0     180000.0
13   342000.0   329900.0   320000.0   329900.0   330445.0     339500.0
14   460000.0   489950.0   445000.0   435000.0   427500.0     435000.0
15   284000.0   288000.0   278950.0   279900.0   306950.0     283000.0
16   265000.0   269000.0   265000.0   271200.0   275000.0     265000.0
17   259995.0   257260.0   259857.5   262499.0   275000.0     257260.0
18   460000.0   475000.0   482450.0   524900.0   484385.0     460000.0
19   319000.0   312500.0   310000.0   309250.0   309950.0     309950.0
20   155000.0   159000.0   164900.0   162500.0   169900.0     159000.0
21   152250.0   150000.0   150000.0   152450.0   155000.0     150000.0
22   299000.0   300000.0   299000.0   300000.0   299999.5     299000.0
23   207000.0   218949.5   214900.0   207450.0   199900.0     207000.0
24   336950.0   337000.0   330000.0   314950.0   324950.0     324950.0
25   279950.0   285000.0   280000.0   284900.0   299900.0     280000.0
26   169900.0   169900.0   169900.0   172500.0   174900.0     169900.0
27   312950.0   315000.0   319000.0   323450.0   329900.0     319000.0
28   229500.0   231240.0   234900.0   249490.0   235000.0     229500.0
29   649000.0   609348.5   580000.0   575000.0   554500.0     595000.0
..        ...        ...        ...        ...        ...          ...
45  1387500.0  1300000.0  1499500.0  1499999.0  1649000.0    1300000.0
46  1325000.0  1292000.0  1299000.0  1100000.0  1125000.0    1299000.0
47   630000.0   656499.0   659900.0   675249.5   689000.0     635499.0
48   399932.0   401744.5   407999.0   410244.5   429999.0     403990.0
49   494950.0   492728.0   493614.0   486200.0   479900.0     494499.5
50   204000.0   223000.0   205500.0   209950.0   199995.0     204000.0
51   345000.0   352450.0   313950.0   310000.0   299500.0     345000.0
52   300000.0   312325.0   309900.0   289900.0   299999.5     312325.0
53   199900.0   194500.0   184900.0   195000.0   198862.0     195000.0
54   499950.0   499000.0   475000.0   469900.0   484688.5     475000.0
55   304700.0   312450.0   299950.0   300000.0   295000.0     299999.0
56   155900.0   156500.0   166075.0   170000.0   170000.0     156500.0
57   167449.5   175000.0   177350.0   175450.0   179900.0     167449.5
58   213000.0   225000.0   220000.0   214900.0   209900.0     210000.0
59   209995.0   210000.0   200000.0   199999.0   218500.0     199999.0
60   179900.0   179995.0   180000.0   179900.0   178950.0     178950.0
61   442000.0   425000.0   418250.0   410909.5   420322.0     419700.0
62   670000.0   649950.0   599000.0   556445.0   555672.5     595000.0
63   479000.0   469900.0   450000.0   439949.5   449000.0     479000.0
64   340000.0   340990.0   339250.0   344990.0   344990.0     339900.0
65   474950.0   474950.0   449000.0   419900.0   425000.0     462000.0
66   389900.0   379450.0   364900.0   364900.0   377487.5     364900.0
67   313217.0   314058.5   315000.0   325000.0   331370.0     314942.5
68   165000.0   165000.0   169999.0   175000.0   179000.0     165000.0
69   153000.0   155000.0   160747.5   159900.0   161500.0     155000.0
70   329500.0   334450.0   329000.0   334900.0   325000.0     325000.0
71   460000.0   499500.0   539500.0   570000.0   489500.0     461950.0
72   251612.0   259900.0   251900.0   253900.0   252400.0     253900.0
73   392500.0   391000.0   389900.0   389900.0   399000.0     389900.0
74   520000.0   509900.0   489000.0   469450.0   447000.0     489000.0

[75 rows x 13 columns]